#!/usr/bin/env bash
# This script displays information about subdomains of a given domain

get_record_type() {
    domain=$1
    sub_domain=$2
    record_type=$(dig $sub_domain.$domain | awk '/ANSWER SECTION/ {getline; print $4}')
    echo $record_type
}

get_destination() {
    domain=$1
    sub_domain=$2
    destination=$(dig $sub_domain.$domain | awk '/ANSWER SECTION/ {getline; getline; print $5}')
    echo $destination
}

domain=$1
sub_domain=$2

if [ -z "$sub_domain" ]; then
    sub_domains=("www" "lb-01" "web-01" "web-02")
else
    sub_domains=("$sub_domain")
fi

for sub in "${sub_domains[@]}"; do
    record_type=$(get_record_type $domain $sub)
    destination=$(get_destination $domain $sub)
    echo "The subdomain $sub is a $record_type record and points to $destination"
done
