#!/usr/bin/env bash
# This is the HAproxy configuration for redirecting HTTP to HTTPS

frontend http_front
    bind *:80
    redirect scheme https code 301 if !{ ssl_fc }

frontend ssl_termination
    bind *:443 ssl crt /etc/ssl/holberton.pem
    reqadd X-Forwarded-Proto:\ https
    default_backend web_servers

backend web_servers
    balance roundrobin
    server web-01 34.198.248.145:80 check
    server web-02 54.89.38.100:80 check
