#!/usr/bin/env bash
# Configure nginx to have a custom 404 page

# Backup default configuration
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Create a custom 404 page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html

# Modify default configuration to use the custom 404 page
sed -i '/server_name _;/a \\n\terror_page 404 /404.html;\n' /etc/nginx/sites-available/default

# Restart nginx
service nginx restart
