#!/usr/bin/env bash
# Configures Nginx with a custom HTTP response header

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Set the custom HTTP response header
sudo sed -i '/server_name _;/a \\tadd_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo systemctl restart nginx
