#!/usr/bin/env bash
# Configures Nginx with custom X-Served-By HTTP response header

# Update and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Replace default Nginx config with custom configuration
cat <<EOF | sudo tee /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    # Custom HTTP header
    add_header X-Served-By \$host;

}
EOF

# Restart Nginx to apply changes
sudo systemctl restart nginx
