#!/usr/bin/env bash
# Install and configure HAProxy as a load balancer

# Update and install HAProxy
sudo apt-get update
sudo apt-get -y install haproxy

# Configure HAProxy
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web1 [STUDENT_ID]-web-01:80 check
    server web2 [STUDENT_ID]-web-02:80 check
EOF

# Restart HAProxy to apply changes
sudo systemctl restart haproxy
