#!/usr/bin/env bash
# This script answers questions about types of networks.

# Question 1
echo "What type of network a computer in local is connected to?"
echo "3"  # LAN

# Question 2
echo "What type of network could connect an office in one building to another office in a building a few streets away?"
echo "2"  # WAN

# Question 3
echo "What network do you use when you browse www.google.com from your smartphone (not connected to the Wifi)?"
echo "1"  # Internet
