#!/usr/bin/env bash
# This script answers questions about MAC and IP addresses.

# Question 1
echo "What is a MAC address?"
echo "2"  # The unique identifier of a network interface

# Question 2
echo "What is an IP address?"
echo "1"  # Is to devices connected to a network what postal address is to houses
