#!/usr/bin/env bash
# This script answers questions about UDP and TCP.

# Question 1
echo "Which statement is correct for the TCP box?"
echo "2"  # It is a protocol that is transferring data in a fast way and might lose data along in the process

# Question 2
echo "Which statement is correct for the UDP box?"
echo "1"  # It is a protocol that is transferring data in a slow way but surely

# Question 3
echo "Which statement is correct for the TCP worker?"
echo "2"  # May I increase the rate at which I am sending you boxes?
