#!/usr/bin/env bash
# This script configures Nginx to listen on port 80

# Update Nginx configuration to listen on port 80
sed -i 's/80 default_server/80 default_server ipv4only=on/' /etc/nginx/sites-available/default

# Restart Nginx service
service nginx restart
