#!/usr/bin/env bash
# This script displays lines containing the bash word to get the PID of the Bash process

ps aux | grep bash | grep -v grep | awk '{print $1, $2, $11}'
# shellcheck disable=SC2009
