#!/usr/bin/env bash
# This script tells a story about each user in /etc/passwd using while loop + IFS

while IFS=':' read -r username x userid groupid info homedir shell;
do
    echo "The user $username is part of the $groupid gang, lives in $homedir and rides $shell. $userid's place is protected by the passcode x, more info about the user here: $info"
done < /etc/passwd
