#!/usr/bin/env bash
# This script groups visitors by IP and HTTP status code, and displays the data using awk

awk '{count[$1,$9]++} END {for (i in count) {split(i, arr, SUBSEP); print count[i], arr[1], arr[2]}}' apache-access.log | sort -nr
