#!/usr/bin/env bash
# This script displays "Best School" 10 times using an until loop

counter=0

# Using an until loop to display "Best School" 10 times
until [ $counter -ge 10 ];
do
    echo "Best School"
    ((counter++))
done
