#!/usr/bin/env bash
# This script gives information about the school file

file="school"

if [ -e "$file" ];
then
    echo "$file exists"

    if [ -s "$file" ];
then
        echo "$file is not empty"

        if [ -f "$file" ];
then
            echo "$file is a regular file"
        fi
    else
        echo "$file is empty"
    fi
else
    echo "$file does not exist"
fi
