#!/usr/bin/env bash
# Configures firewall on web-01

# Update and install ufw
sudo apt-get update
sudo apt-get install ufw -y

# Enable ufw and allow specific ports
sudo ufw enable
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Block all other incoming traffic
sudo ufw default deny incoming

# Display ufw status
sudo ufw status numbered
