#!/usr/bin/env bash
# Configures firewall on web-01

# Install ufw
sudo apt-get update
sudo apt-get install ufw -y

# Enable ufw
sudo ufw enable

# Allow incoming traffic on ports 22, 443, and 80
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Block all other incoming traffic
sudo ufw default deny incoming

# Show ufw status for verification
sudo ufw status numbered
