#!/bin/bash

# Backup the original hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Modify the hosts file to change localhost and facebook.com IP addresses
sudo sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts
sudo sed -i 's/157.240.11.35/8.8.8.8/g' /etc/hosts

# Display the modified hosts file
cat /etc/hosts
