#!/usr/bin/env bash

# This script runs the whoami command as the user passed as an argument

if [ $# -eq 1 ]; then
  sudo -n whoami -u "$1"
else
  echo "Please provide one argument: the username"
fi
