#!/usr/bin/env bash
# This script configures Nginx to run as the nginx user, listening on port 8080

sed -i 's/user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
nginx
