#!/usr/bin/env bash
# This script connects to the server using the user 'ubuntu' and the SSH key ~/.ssh/school

ssh -i ~/.ssh/school ubuntu@server01

# Exit the session after the connection is closed
exit
