#!/usr/bin/env bash
# This script adds the provided SSH public key to the ubuntu user's authorized_keys file.

# SSH Public Key
ssh_public_key="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCjjT0UAlUWbQ2E8D9y43b4HeSXFwShM8b9nh4ot739/kVqoSS5bDXfNc2W9F6eDGgzgEePvjyi3XPyc20s8sLLoBhYhpzLlL3H6QsrLIQO4RStfIEg/94Rd0n9NTUACHYOC63CfLCPFLmcK4vBtPUjMtr0j5Yd8sJBWR4V/16I8qDJVNgjCS2sryfeXkKpqGLUlHnpukfqA6JyDBxDfyO0kjP2L/Vkaa9SW0n5NuomSPgsCLj9PE1vbTMDhRka5Jtg8ARbJRGvynHSKdRGMEr7neeb41cekZPZD5wa15AX7yzriczCQ/ZP/9PEUrWqPJ9Qq8coiFEfi/xdezUlKBf2O6tNAK3/OSqRN5JV8Uw5BkBuZRw9k7TenpXpdk2gshg8/q0/uVm7iolJKG0xTtmM9m2Tys4lTPownWhRFFpm8dQ1/tZVWOcvQKhVJ+ad/UadX0QDhF/EaaI7BmFTWhCCjOF4o3s9ROX2hC7ZDjfrSfK4tpROYhePl7EwHPSdH+8= root@79d7ee47117a"

# Add SSH Public Key to authorized_keys for ubuntu user
echo "$ssh_public_key" >> /home/ubuntu/.ssh/authorized_keys

# Output a message
echo "SSH public key added to authorized_keys for ubuntu user."
